name: .NET Core

on: 
  push:
    branches: archna
    paths: [apis/poi/**,.github/workflows/workflowarchna.yml]
  pull_request:
    branches: master
    paths: [apis/poi/**,.github/workflows/workflowarchna.yml]

jobs:
  build:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore apis/poi/web/poi.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore apis/poi/web/poi.csproj
    - name: Test      
      run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests/UnitTests.csproj 
    - name: Open Github Issue
      if: ${{ failure() }}
      uses: rishabhgupta/git-action-issue@v2
      id: Issue
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Automated Issue creation
          body: This issue is created because tests have failed
          assignees: 'archnaaju'
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: POI_Docker_Image
        path: apis/poi/web/
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}}
         registry: docker.pkg.github.com
         file: apis/poi/web/Dockerfile
         context: apis/poi/web/
         repository: mphasis-hackthon/openhack-devops-team/poiservice
         tag_with_sha: true
    
